### PR TITLE
fix: make iframe area 0(#29)

### PR DESCRIPTION
**Pull request by jung-han**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* visibility: 'hidden' 속성 때문에 영역이 그대로 잡혀있어 스타일에 영향을 줌.

image

* width, height 를 0으로 수정

#29 

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by jung-han** [comment]
ok to test

**Comment by jung-han** [comment]
ok to test

**Comment by seonim-ryu** [comment]
[3/25] 이견 없습니다. 👍

**Comment by junghwan-park** [comment]
[3/25] 이견 없습니다.

**Pull request merged**
